# Implementing in TensorFlow

An introduction to how-to-do-Implementation in TensorFlow with some of the most important functions for Python-users. A full API can be found on the TensorFlow wedside:

https://www.tensorflow.org/

For installation and complementry knowlegde about how implement Deep Learning networks in TensorFlow I can highly recommend:

https://github.com/alrojo/tensorflow-tutorial


In [7]:
import tensorflow as tf
from tensorflow.python.framework.ops import reset_default_graph
sess = tf.Session() # For printing the output

Numbers
===

$\textbf{Constants}$

In [2]:
x = tf.constant(5, dtype=tf.int32) # x = 5, int
y = tf.constant(7.4, dtype=tf.float32) # y = 7.4, float

print(sess.run(x))
print(sess.run(y))

5
7.4


$\textbf{Casting}$

In [3]:
x = tf.to_float(x) # 5.0 = 5, float

print(sess.run(x))

5.0


$\textbf{Arithmetric Operation}$

In [62]:
x = tf.constant(5, dtype=tf.float32) # x = 5
y = tf.constant(7.4, dtype=tf.float32) # y = 7.4

z = tf.add(x,y) # 12.4 = 5 + 7
u = tf.subtract(x,y) # -2.4 = 5 - 7

print(sess.run(z))
print(sess.run(u))

12.4
-2.4


$\textbf{Basic Math Functions}$

In [66]:
x = tf.constant(5, dtype=tf.float32) # x = 5
y = tf.constant(7.4, dtype=tf.float32) # y = 7.4

z = tf.negative(x) # -5 = negative(5)
u = tf.round(y) # 7 = round(7.4)
v = tf.exp(x) # 148.413 = exp(5)

print(sess.run(z))
print(sess.run(u))
print(sess.run(v))

-5.0
7.0
148.413


Array
===

$\textbf{Constant Arrays}$

In [6]:
a = tf.constant([1,2], dtype=tf.int32) # a = [1,2]
print(sess.run(a))

[1 2]


In [7]:
b = tf.constant([[1,2],[3,4]], dtype=tf.int32) # b = [[1,2],[3,4]]
print(sess.run(b))

[[1 2]
 [3 4]]


In [8]:
c = tf.constant([[1,2],[3,4],[5,6]], dtype=tf.int32) # c = [[1,2],[3,4],[5,6]]
print(sess.run(c))

[[1 2]
 [3 4]
 [5 6]]


In [9]:
d = tf.zeros([2,2,3], dtype=tf.float32) # array containing only zeros of shape [2,2,3]
print(sess.run(d))

[[[ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]]]


In [10]:
e = tf.ones([2,3,4], dtype=tf.int32) # array containing only ones of shape [2,3,4]
print(sess.run(e))

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [11]:
f = tf.fill([2,3,4], 2) # array containing only twos of shape [2,3,4]
print(sess.run(f))

[[[2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]]

 [[2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]]]


$\textbf{Get Shape}$

In [67]:
f = tf.fill([2,3,4], 2)

f.get_shape() # the shape of a Tensor

TensorShape([Dimension(2), Dimension(3), Dimension(4)])

Random Numbers
===

In [13]:
g = tf.random_normal([2,2], mean=0, stddev=1)
# number from random standard normal distribution

print(sess.run(g))

[[ 1.36225629 -1.04141688]
 [-0.40665796 -0.67176461]]


In [14]:
h = tf.random_uniform([2,2,2], minval=0, maxval=5, dtype=tf.int32) 
# random uniform distribution between [0, 5) and shape [2,2,2]

print(sess.run(h))

[[[1 3]
  [4 4]]

 [[2 4]
  [4 2]]]


In [15]:
h = tf.random_uniform([2,2], minval=0, maxval=5, dtype=tf.int32, seed=1234)
# random uniform distribution between [0, 5) with seed

print(sess.run(h))

[[4 0]
 [3 4]]


Array Indexing
===

This follow the exact index as in Numpy

In [16]:
index_array = tf.constant([[1,2,3,4],[5,6,7,8],[9,10,11,12]], dtype=tf.int32)
print(sess.run(index_array))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
print(sess.run(index_array[1,:])) # second row of the index matrix

[5 6 7 8]


In [18]:
print(sess.run(index_array[:,1])) # second column af the index matrix

[ 2  6 10]


In [19]:
print(sess.run(index_array[0,0:2])) # second column af the index matrix

[1 2]


Working with Arrays
===

Transpose

In [58]:
A = tf.constant([[1,2],[3,4]], dtype=tf.int32)

A_Transpose = tf.transpose(a)

print("A")
print(sess.run(a))
print("A Transposed")
print(sess.run(a_Transpose))

A
[[1 2]
 [3 4]]
A Transposed
[[1 3]
 [2 4]]


Multiply Matrices

In [60]:
a = tf.constant([[1,2],[3,4]],dtype=tf.int32)
b = tf.constant([[5,6],[7,8]],dtype=tf.int32)

c = tf.matmul(a,b) # c = a*b

print(sess.run(c))

[[19 22]
 [43 50]]


Expand dimensions

In [68]:
a = tf.constant([[1,2],[3,4]], dtype=tf.int32)

# Numpy:
# b = np.expand_dims(a, axis=1) # n x c

# TensorFlow
b = tf.expand_dims(a, axis = 1)

print(sess.run(b))

[[[1 2]]

 [[3 4]]]


Maximum

In [72]:
a = tf.constant([[1,2],[3,4]], dtype=tf.int32)

# Numpy:
#b  = np.max(z, axis = 1)

# TensorFlow
b = tf.reduce_max(a, reduction_indices = 1)

print(sess.run(b))

[2 4]


Sum

In [73]:
a = tf.constant([[1,2],[3,4]], dtype=tf.int32)

# Numpy
# b = np.sum(a, axis = 1)
    
b = tf.reduce_sum(a, axis = 1)

print(sess.run(b))

[3 7]


Move axis

In [5]:
# Numpy
# a = np.zeros([10,100,3,6]) # shape = (10,100,3,6)
# np.moveaxis(a,1,3).shape # shape = (10,3,6,100)

# TensorFlow
a = tf.zeros((10,100,3,6)) # shape = (10,100,3,6)
tf.transpose(a,[0,2,3,1]) # shape = (10,3,6,100)

<tf.Tensor 'transpose:0' shape=(10, 3, 6, 100) dtype=float32>

# Looping

Loop that add numbers from 1 to 10 together.

In [34]:
# loop function
def body(X,idx,out):
    out = tf.add(out,X[idx]) # out = out + X[idx]
    idx = idx + 1
    return X, idx, out

# stoping criterium
def condition(X,idx,out):
    return tf.less(idx,10)

# initializing the input
X_in = tf.constant(range(1,11),dtype=tf.int32)
idx_in = tf.constant(0,dtype=tf.int32)
out_in = tf.constant(0,dtype=tf.int32)

with tf.Session():
    tf.global_variables_initializer().run()
    
    # TensorFlow loop
    _, _, out_out = tf.while_loop(condition, body, [X_in,idx_in,out_in])
    
    print(out_out.eval())

55


Creating four 2x2 arrays with random numbers and adding these together to get the cumulative sum of each element.

In [33]:
# loop function
def body(X,idx,X_cum):
    X_cum = tf.add(X_cum,X[:,:,idx])
    idx = idx + 1
    return X, idx, X_cum

# stoping criterium
def condition(X,idx,out):
    return tf.less(idx,4)

# initializing the input
X_in = tf.random_uniform([2,2,4], minval=0, maxval=5, dtype=tf.int32)
X_cum = tf.constant([[0,0],[0,0]],dtype=tf.int32)
idx_in = tf.constant(0,dtype=tf.int32)

with tf.Session():
    tf.global_variables_initializer().run()
    
    # TensorFlow loop
    _, _, X_cum = tf.while_loop(condition, body, [X_in,idx_in,X_cum])
    
    print(X_cum.eval())

[[ 8  3]
 [ 7 10]]


# Conditioning

Conditioning with constants.

In [42]:
i = tf.constant(10, dtype=tf.int32)

a = tf.constant(4, dtype=tf.int32)
b = tf.constant(8, dtype=tf.int32)

y = tf.cond(tf.less(15, i), # 15 < 10
            lambda: a, # if TRUE
            lambda: b) # if FALSE

print(sess.run(y))

8


Conditioning with functions.

In [50]:
i = tf.constant(10, dtype=tf.int32)

x = tf.constant([[1,2],[3,4]], dtype=tf.int32)
W = tf.constant([[5,6],[7,8]], dtype=tf.int32)
b = tf.constant([9,10], dtype=tf.int32)

def LM_Plus(data, weights, bias):
    y = tf.add(tf.matmul(data, weights),bias) # x*W + b
    return y

def LM_Minus(data, weights, bias):
    y = tf.subtract(tf.matmul(data, weights),bias) # x*W - b
    return y

pred = tf.cond(tf.greater(i,3), # 10 > 3
              lambda: LM_Plus(x,W,b), # if TRUE
              lambda: LM_Minus(x,W,b)) # if FALSE

print(sess.run(pred))

[[28 32]
 [52 60]]


# Training a Simple Linear Model on random generated data

In [106]:
reset_default_graph()

sess = tf.Session()

# generate 100 training points
x_train = tf.random_uniform(shape=[100,3],minval=2,maxval=6)
y_train = tf.random_uniform(shape=[100,2],minval=0,maxval=1,dtype=tf.int32)

# generate 10 validation points
x_valid = tf.random_uniform(shape=[10,3],minval=1,maxval=6)
y_valid = tf.random_uniform(shape=[10,2],minval=0,maxval=1, dtype=tf.int32)

# initializing Weights and Biases

weight_initializer = tf.truncated_normal_initializer(stddev=0.1)
Weight = tf.get_variable('Weights',[3, 2],initializer=weight_initializer)
Bias = tf.get_variable('Bias',[2],initializer=tf.constant_initializer(0.0))




#Weight = tf.truncated_normal([3,2], stddev=0.1, dtype=tf.float32)
#Bias = tf.constant(0.1, shape=[2], dtype=tf.float32)

# Placeholder for input and output
x_pl = tf.placeholder(tf.float32, [None, 3])
y_pl = tf.placeholder(tf.float32, [None, 2])

# Making the model
y_pred = tf.matmul(x_pl,Weight) + Bias

init = tf.initialize_all_variables()
sess.run(init)    

# Cost Function
cross_entropy = tf.reduce_mean(-tf.reduce_sum(y_pl * tf.log(y_pred), reduction_indices=[1]))

# Optimizer - minimizing the cross entropy
optimizer = tf.train.AdamOptimizer(learning_rate=0.25).minimize(cross_entropy)

# Accuracy
correct_prediction = tf.equal(tf.argmax(y_pl, 1), tf.argmax(y_pred, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

# Training our model
feed_dict_train = {x_pl: x_train, y_pl: y_train}
fetches_train = [optimizer, cross_entropy]
res = sess.run(fetches=fetches_train, feed_dict=feed_dict_train)
train_cost =res[1]
    
feed_dict_valid = {x_pl: x_valid, y_pl: y_valid}

fetches_valid = [cross_entropy, accuracy]
res = sess.run(fetches=fetches_valid, feed_dict=feed_dict_valid)

val_cost = res[0]
val_acc = res[1]






Instructions for updating:
Use `tf.global_variables_initializer` instead.


TypeError: The value of a feed cannot be a tf.Tensor object. Acceptable feed values include Python scalars, strings, lists, or numpy ndarrays.

In [94]:
y_test

<tf.Tensor 'ToDouble_1:0' shape=(10, 2, 2) dtype=float64>