# Implementing in TensorFlow

Tensorflow is a strong tool for solving Deep Learning tasks, especially tasks that can be solved by just putting various blocks together. This is a guide that goes beyond that, and gives an introduktion to some of the most commondly used functions needed for implementing coustum made code in Tensorflow. It is especially good if you are new to Python and coding in general.

This guide is based on how the solutions would be made in Numpy.

Most function needed can be found in the TensorFlow API:

https://www.tensorflow.org/

Some functions are yet to come.

For installation and complementary knowledge about how to implement Deep Learning networks in TensorFlow I can highly recommend:

https://github.com/alrojo/tensorflow-tutorial


In [50]:
import tensorflow as tf
import numpy as np
from tensorflow.python.framework.ops import reset_default_graph
sess = tf.Session() # For printing the output

Numbers
===

$\textbf{Constants}$

In [2]:
x = tf.constant(5, dtype=tf.int32) # x = 5, int
y = tf.constant(7.4, dtype=tf.float32) # y = 7.4, float

print(sess.run(x))
print(sess.run(y))

5
7.4


$\textbf{Casting}$

In [3]:
x = tf.to_float(x) # 5.0 = 5, float

print(sess.run(x))

5.0


$\textbf{Arithmetric Operation}$

In [6]:
x = tf.constant(5, dtype=tf.float32) # x = 5
y = tf.constant(7.4, dtype=tf.float32) # y = 7.4

z = tf.add(x,y) # 12.4 = 5 + 7
u = tf.sub(x,y) # -2.4 = 5 - 7

print(sess.run(z))
print(sess.run(u))

12.4
-2.4


$\textbf{Basic Math Functions}$

In [9]:
x = tf.constant(5, dtype=tf.float32) # x = 5
y = tf.constant(7.4, dtype=tf.float32) # y = 7.4

z = tf.neg(x) # -5 = negative(5)
u = tf.round(y) # 7 = round(7.4)
v = tf.exp(x) # 148.413 = exp(5)

print(sess.run(z))
print(sess.run(u))
print(sess.run(v))

-5.0
7.0
148.413


Array
===

**Constant Arrays**

In [10]:
a = tf.constant([1,2], dtype=tf.int32) # a = [1,2]
print(sess.run(a))

[1 2]


In [11]:
b = tf.constant([[1,2],[3,4]], dtype=tf.int32) # b = [[1,2],[3,4]]
print(sess.run(b))

[[1 2]
 [3 4]]


In [12]:
c = tf.constant([[1,2],[3,4],[5,6]], dtype=tf.int32) # c = [[1,2],[3,4],[5,6]]
print(sess.run(c))

[[1 2]
 [3 4]
 [5 6]]


In [13]:
d = tf.zeros([2,2,3], dtype=tf.float32) # array containing only zeros of shape [2,2,3]
print(sess.run(d))

[[[ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]]]


In [14]:
e = tf.ones([2,3,4], dtype=tf.int32) # array containing only ones of shape [2,3,4]
print(sess.run(e))

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [15]:
f = tf.fill([2,3,4], 2) # array containing only twos of shape [2,3,4]
print(sess.run(f))

[[[2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]]

 [[2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]]]


**Get Shape**

In [20]:
f = tf.fill([2,3,4], 2)

print(f.get_shape())
print(f.get_shape()[0]) # the shape of a Tensor

(2, 3, 4)
2


Random Numbers
===

In [21]:
g = tf.random_normal([2,2], mean=0, stddev=1)
# number from random standard normal distribution

print(sess.run(g))

[[-0.03874318 -1.03920794]
 [-1.1802808  -1.72704375]]


In [22]:
h = tf.random_uniform([2,2,2], minval=0, maxval=5, dtype=tf.int32) 
# random uniform distribution between [0, 5) and shape [2,2,2]

print(sess.run(h))

[[[0 4]
  [0 0]]

 [[0 2]
  [1 0]]]


In [23]:
h = tf.random_uniform([2,2], minval=0, maxval=5, dtype=tf.int32, seed=1234)
# random uniform distribution between [0, 5) with seed

print(sess.run(h))

[[4 0]
 [3 4]]


Array Indexing
===

This follow the Python indexing.

In [24]:
index_array = tf.constant([[1,2,3,4],[5,6,7,8],[9,10,11,12]], dtype=tf.int32)
print(sess.run(index_array))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
print(sess.run(index_array[1,:])) # second row of the index matrix

[5 6 7 8]


In [26]:
print(sess.run(index_array[:,1])) # second column af the index matrix

[ 2  6 10]


In [27]:
print(sess.run(index_array[0,0:2])) # second column af the index matrix

[1 2]


Working with Arrays
===

**Transpose**

In [31]:
A = tf.constant([[1,2],[3,4]], dtype=tf.int32)

A_Transpose = tf.transpose(A)

print("A")
print(sess.run(A))
print("A Transposed")
print(sess.run(A_Transpose))

A
[[1 2]
 [3 4]]
A Transposed
[[1 3]
 [2 4]]


**Multiply Matrices**

In [32]:
a = tf.constant([[1,2],[3,4]],dtype=tf.int32)
b = tf.constant([[5,6],[7,8]],dtype=tf.int32)

c = tf.matmul(a,b) # c = a*b

print(sess.run(c))

[[19 22]
 [43 50]]


**Expand dimensions**

In [44]:
a = tf.constant([[1,2],[3,4]], dtype=tf.int32)

# Numpy:
# b = np.expand_dims(a, axis=0) # n x c

# TensorFlow
b = tf.expand_dims(a,dim=0)

print(a.get_shape())
print(b.get_shape())


(2, 2)
(1, 2, 2)


**Maximum**

In [45]:
a = tf.constant([[1,2],[3,4]], dtype=tf.int32)

# Numpy:
#b  = np.max(z, axis = 1)

# TensorFlow
b = tf.reduce_max(a, reduction_indices = 1)

print(sess.run(b))

[2 4]


**Sum**

In [42]:
a = tf.constant([[1,2],[3,4]], dtype=tf.int32)

# Numpy
# b = np.sum(a, axis = 1)
    
b = tf.reduce_sum(a,reduction_indices=1)

print(sess.run(b))

[3 7]


**Move axis**

In [49]:
# Numpy
# a = np.zeros([10,100,3,6]) # shape = (10,100,3,6)
# np.moveaxis(a,1,3).shape # shape = (10,3,6,100)

# TensorFlow
a = tf.zeros((10,100,3,6)) # shape = (10,100,3,6)
print(sess.run(tf.transpose(a,[0,2,3,1])).shape) # shape = (10,3,6,100)

(10, 3, 6, 100)


**Dot**

Inner product of matrices.

In [65]:
# Numpy
# A = np.zeros([100,3,6]) # shape = (100,3,6)
# B = np.zeros([6,6]) # shape = (6,6)
# C = np.dot(A,B) # shape = (100,3,6)

def dotTensorFlow(a, b):
    shape = tf.shape(a)
    rank = shape.get_shape()[0].value
    a = tf.expand_dims(a, rank)
    ab = tf.mul(a, b)
    return tf.reduce_sum(ab, rank-1)


A = tf.zeros([100,3,6]) # shape = (100,3,6)
B = tf.zeros([6,6]) # shape = (6,6)
C = dotTensorFlow(A,B) # shape = (100,3,6)

print(sess.run(C).shape) # shape = (10,3,6)


(100, 3, 6)


# Looping

Loop that add numbers from 1 to 10 together.

In [34]:
# loop function
def body(X,idx,out):
    out = tf.add(out,X[idx]) # out = out + X[idx]
    idx = idx + 1
    return X, idx, out

# stoping criterium
def condition(X,idx,out):
    return tf.less(idx,10)

# initializing the input
X_in = tf.constant(range(1,11),dtype=tf.int32)
idx_in = tf.constant(0,dtype=tf.int32)
out_in = tf.constant(0,dtype=tf.int32)

with tf.Session():
    tf.global_variables_initializer().run()
    
    # TensorFlow loop
    _, _, out_out = tf.while_loop(condition, body, [X_in,idx_in,out_in])
    
    print(out_out.eval())

55


Creating four 2x2 arrays with random numbers and adding these together to get the cumulative sum of each element.

In [33]:
# loop function
def body(X,idx,X_cum):
    X_cum = tf.add(X_cum,X[:,:,idx])
    idx = idx + 1
    return X, idx, X_cum

# stoping criterium
def condition(X,idx,out):
    return tf.less(idx,4)

# initializing the input
X_in = tf.random_uniform([2,2,4], minval=0, maxval=5, dtype=tf.int32)
X_cum = tf.constant([[0,0],[0,0]],dtype=tf.int32)
idx_in = tf.constant(0,dtype=tf.int32)

with tf.Session():
    tf.global_variables_initializer().run()
    
    # TensorFlow loop
    _, _, X_cum = tf.while_loop(condition, body, [X_in,idx_in,X_cum])
    
    print(X_cum.eval())

[[ 8  3]
 [ 7 10]]


# Conditioning

**Conditioning with constants**

In [42]:
i = tf.constant(10, dtype=tf.int32)

a = tf.constant(4, dtype=tf.int32)
b = tf.constant(8, dtype=tf.int32)

y = tf.cond(tf.less(15, i), # 15 < 10
            lambda: a, # if TRUE
            lambda: b) # if FALSE

print(sess.run(y))

8


**Conditioning with functions**

In [50]:
i = tf.constant(10, dtype=tf.int32)

x = tf.constant([[1,2],[3,4]], dtype=tf.int32)
W = tf.constant([[5,6],[7,8]], dtype=tf.int32)
b = tf.constant([9,10], dtype=tf.int32)

def LM_Plus(data, weights, bias):
    y = tf.add(tf.matmul(data, weights),bias) # x*W + b
    return y

def LM_Minus(data, weights, bias):
    y = tf.subtract(tf.matmul(data, weights),bias) # x*W - b
    return y

pred = tf.cond(tf.greater(i,3), # 10 > 3
              lambda: LM_Plus(x,W,b), # if TRUE
              lambda: LM_Minus(x,W,b)) # if FALSE

print(sess.run(pred))

[[28 32]
 [52 60]]
